Repository pfnet-research/k8s-cluster-simulator, pull requests merged in 2019-04, with the labels that each got.

#179 Update README.md
  README.md
Labels: docs

#190 Fix links to coveralls badge and webpage
  README.md
Labels: docs

#197 Update travis badge URL
  README.md
Labels: docs

#200 Fix comments
  example/main.go
  pkg/kubesim.go
Labels: docs

#204 Fix panic on Node.DeletePod()
  pkg/node/node.go
Labels: bug

#206 Make Travis call goveralls after build success
  .travis.yml
Labels: CI, enhancement

#203 Hide profile.cov
  .gitignore
  .travis.yml
  Makefile
Labels: CI, cleanup

#207 Fix license scripts
  scripts/license/add.py
  scripts/license/check.py
Labels: bug
